version: '3.3'

services:
    webserver:
        build: ./bin/php/${PHP_VERSION}
        container_name: '${PROJECT_NAME}-${PHP_VERSION}'
        restart: 'always'
        ports:
            - "${HOST_HTTP_PORT}:80"
            - "${HOST_HTTPS_PORT}:443"
        depends_on: 
            - database
        volumes:
            - ${DOCUMENT_ROOT-./www}:${APACHE_DOCUMENT_ROOT}
            - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini}
            - ${VHOSTS_DIR-./config/vhosts}://etc/apache2/sites-enabled
            - ${LOG_DIR-./logs/apache2}:/var/log/apache2
        networks:
            - backend

    database:
        build: ./bin/mysql/${DATABASE_VERSION}
        container_name: '${PROJECT_NAME}-${DATABASE_VERSION}'
        restart: 'always'
        ports:
            - "127.0.0.1:${HOST_MYSQL_PORT}:3306"
        volumes:
            - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: '${PROJECT_NAME}-phpmyadmin'
        restart: always
        ports:
            - "127.0.0.1:${HOST_PMA_PORT}:80"
        depends_on: 
            - database
        environment: 
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes: 
            - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    
    redis:
        image: redis:latest
        container_name: '${PROJECT_NAME}-redis'
        ports:
            - "127.0.0.1:${HOST_REDIS_PORT}:6379"
    
networks:
    backend:
        name: backend-network