version: '3.3'

services:
    apache:
        build: ./php
        container_name: docker_apache
        ports:
            - "81:80"
            - "444:444"
        depends_on: 
            - mysql
        volumes:
            - ./www:/var/www/html
    mysql:
        image: mysql:8.0
        container_name: docker_mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "8080:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: docker_phpmyadmin
        restart: always
        ports:
            - "8888:80"
        depends_on: 
            - mysql
        environment: 
            PMA_HOST: mysql